services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-xyz}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-123}
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.docker/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - api-network
    healthcheck:
      test: curl -s http://localhost:4566 > /dev/null 2>&1
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    container_name: ranking-api
    build:
      context: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .envrc
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - api-network

networks:
  api-network:
    driver: bridge